---
title: "viz_part_01"
author: "Jiajun Tao"
date: "2022-09-29"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Import data

```{r}
library(tidyverse)
library(ggridges)
```


```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```
Let's make a scatter plot

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax))+
  geom_point()
```

Let's make the same scatterplot, but different

```{r}
weather_df %>% 
  drop_na() %>% 
  filter(name == "CentralPark_NY") %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()
```

```{r}
weather_scatterplot = 
  weather_df %>% 
  drop_na() %>% 
  ggplot(aes(x = tmin, y = tmax))

weather_scatterplot +
  geom_point()
```

#Let's make fancy

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .3) +
  geom_smooth()
```

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point(aes(color = name)) +
  geom_smooth(se = FALSE)
```

make separate panels.

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point() +
  geom_smooth(se = FALSE) +
  facet_grid(name ~ .)
```


```{r}
weather_df %>% 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point(aes(size = prcp),alpha = .3) +
  geom_smooth(se = FALSE) +
  facet_grid(. ~ name)
```

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_hex()
```


```{r}
weather_df %>% 
  ggplot(aes(x = tmax, fill = name)) +
  geom_histogram() +
  facet_grid(.~name)
```



More options

```{r}
weather_df %>% 
  ggplot(aes(x = tmax, fill = name)) +
  geom_density(alpha = .3)
```

```{r}
weather_df %>% 
  ggplot(aes(x = name, y = tmax)) +
  geom_boxplot()
```

```{r}
weather_df %>% 
  ggplot(aes(x = name, y = tmax, fill = name)) +
  geom_violin()
```

OR



```{r}
weather_df %>% 
  ggplot(aes(x = tmax, y = name)) +
  geom_density_ridges()
```

Saving and embedding plots 

First, save a plot

```{r}
weather_scatterplot =
  weather_df %>% 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point(aes(size = prcp), alpha = .3)+
  geom_smooth(se = FALSE) +
  facet_grid(. ~ name)

weather_scatterplot

ggsave(
  file = "results/weather_scatterplot.pdf", 
  plot = weather_scatterplot,
  width = 8, height = 5)
```

```{r fig.width=10}

```

